<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>f5c8c427-19a0-41ab-9302-2523c2087cfd</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Anthropic.SDK" Version="5.10.0" />
		<PackageReference Include="OpenAI" Version="2.11.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
	</ItemGroup>

</Project>